### ISSUE TITLE
关于在encoding trajectory阶段反复出现的‘已杀死’问题

### ISSUE THREAD

**Issue by KeFttan** [aptx1231/Bigscity-TrafficDL-Datasets#48]
一开始完全按照指引操作出现报错，似乎是显卡算力问题：
![REGR4NI~MA0{)LKN8 `79OI](https://github.com/LibCity/Bigscity-LibCity-Datasets/assets/133731050/5e6b7e89-2a8d-41cb-a0ad-231a4b0d6d0e)
于是尝试安装新版cuda:
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
由于requirements.txt中的torch版本较低，所以我删去了那一行，使用的是安装新cuda对应的torch版本；但是后续尝试了很多次，都会出现相同的错误：即在“encoding trajectory”阶段出现“已杀死”
PS：内存64g没有出现内存不够的情况，且没有他人进行kill
![80b0ba7c608b845718ca743fa371466](https://github.com/LibCity/Bigscity-LibCity-Datasets/assets/133731050/915e1df6-255a-4b4f-ac03-a75d5d6aab56)

**Comment by WenMellors** [comment]
您好，下次记得 https://github.com/LibCity/Bigscity-LibCity 在这个仓库提。

目前，从您的截图看不出什么问题。您可以打开任务管理器（如果是 windows）或者 htop (Linux 环境) 实时观察一下内存的使用情况。

**Comment by KeFttan** [comment]
好的，感谢您的回复！
